// <auto-generated />
using System;
using LoveSushiPMR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoveSushiPMR.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.BonusAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BonusAccounts");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconUrl = "🍣",
                            IsActive = true,
                            Name = "Суши и роллы",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IconUrl = "🍱",
                            IsActive = true,
                            Name = "Сеты",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IconUrl = "🍜",
                            IsActive = true,
                            Name = "Лапша WOK",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IconUrl = "🍕",
                            IsActive = true,
                            Name = "Пицца",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IconUrl = "🥗",
                            IsActive = true,
                            Name = "Салаты",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            IconUrl = "🥣",
                            IsActive = true,
                            Name = "Супы",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            IconUrl = "🥤",
                            IsActive = true,
                            Name = "Напитки",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            IconUrl = "🍰",
                            IsActive = true,
                            Name = "Десерты",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Couriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Иванов Иван",
                            Phone = "+373-777-12-34",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Петров Пётр",
                            Phone = "+373-777-56-78",
                            Status = 0
                        });
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.DeliveryAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartment")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("DeliveryZoneId")
                        .HasColumnType("integer");

                    b.Property<string>("Entrance")
                        .HasColumnType("text");

                    b.Property<string>("Floor")
                        .HasColumnType("text");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Intercom")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryZoneId");

                    b.HasIndex("UserId");

                    b.ToTable("DeliveryAddresses");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.DeliveryZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DeliveryPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxDeliveryTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MinDeliveryTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeliveryZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryPrice = 0m,
                            IsActive = true,
                            MaxDeliveryTimeMinutes = 50,
                            MinDeliveryTimeMinutes = 30,
                            Name = "Центр города"
                        },
                        new
                        {
                            Id = 2,
                            DeliveryPrice = 150m,
                            IsActive = true,
                            MaxDeliveryTimeMinutes = 60,
                            MinDeliveryTimeMinutes = 40,
                            Name = "Спутник"
                        },
                        new
                        {
                            Id = 3,
                            DeliveryPrice = 100m,
                            IsActive = true,
                            MaxDeliveryTimeMinutes = 55,
                            MinDeliveryTimeMinutes = 35,
                            Name = "Западный"
                        },
                        new
                        {
                            Id = 4,
                            DeliveryPrice = 100m,
                            IsActive = true,
                            MaxDeliveryTimeMinutes = 55,
                            MinDeliveryTimeMinutes = 35,
                            Name = "Северный"
                        });
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("WeightGrams")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Лосось, сыр филадельфия, огурец, нори",
                            ImageUrl = "/images/dishes/philadelphia.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            Name = "Филадельфия классик",
                            Price = 420m,
                            WeightGrams = 250
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Краб-микс, огурец, авокадо, икра тобико, нори",
                            ImageUrl = "/images/dishes/california.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            Name = "Калифорния",
                            Price = 380m,
                            WeightGrams = 220
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Угорь, огурец, соус унаги, кунжут",
                            ImageUrl = "/images/dishes/dragon.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            Name = "Дракон",
                            Price = 520m,
                            WeightGrams = 280
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Филадельфия классик, Калифорния, Спайси ролл, Сяке маки - 32 шт.",
                            ImageUrl = "/images/dishes/set-love.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            Name = "Сет 'Любовь'",
                            Price = 1450m,
                            WeightGrams = 1000
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "12 видов роллов - 64 шт. Идеально для компании!",
                            ImageUrl = "/images/dishes/set-family.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            Name = "Сет 'Семейный'",
                            Price = 2800m,
                            WeightGrams = 2200
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Лапша удон, курица, овощи, соус терияки",
                            ImageUrl = "/images/dishes/wok-chicken.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            Name = "WOK с курицей",
                            Price = 350m,
                            WeightGrams = 350
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Лапша рисовая, креветки, овощи, соус острый",
                            ImageUrl = "/images/dishes/wok-shrimp.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            Name = "WOK с креветками",
                            Price = 450m,
                            WeightGrams = 350
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Томатный соус, моцарелла, базилик",
                            ImageUrl = "/images/dishes/pizza-margarita.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            Name = "Пицца 'Маргарита'",
                            Price = 380m,
                            WeightGrams = 550
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Томатный соус, моцарелла, пепперони",
                            ImageUrl = "/images/dishes/pizza-pepperoni.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            Name = "Пицца 'Пепперони'",
                            Price = 450m,
                            WeightGrams = 600
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Курица, салат романо, сыр пармезан, соус цезарь, крутоны",
                            ImageUrl = "/images/dishes/salad-caesar.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            Name = "Цезарь с курицей",
                            Price = 320m,
                            WeightGrams = 250
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Тофу, водоросли вакаме, лук зелёный",
                            ImageUrl = "/images/dishes/soup-miso.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            Name = "Мисо суп",
                            Price = 120m,
                            WeightGrams = 300
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            Description = "Освежающий напиток",
                            ImageUrl = "/images/dishes/cola.jpg",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            Name = "Coca-Cola 0.5л",
                            Price = 80m,
                            WeightGrams = 500
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            Description = "Классический итальянский десерт",
                            ImageUrl = "/images/dishes/tiramisu.jpg",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = false,
                            Name = "Тирамису",
                            Price = 250m,
                            WeightGrams = 150
                        });
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualDeliveryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BonusUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("CourierId")
                        .HasColumnType("integer");

                    b.Property<int>("DeliveryAddressId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("EstimatedDeliveryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<int?>("PromoCodeId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UtensilsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PaymentId");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conditions")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Скидка 20% с 12:00 до 15:00",
                            DiscountPercent = 20m,
                            EndDate = new DateTime(2027, 2, 22, 12, 58, 59, 34, DateTimeKind.Utc).AddTicks(1652),
                            ImageUrl = "/images/promos/happy-hours.jpg",
                            IsActive = true,
                            Name = "Счастливые часы",
                            StartDate = new DateTime(2025, 2, 22, 12, 58, 59, 34, DateTimeKind.Utc).AddTicks(1636)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Скидка 15% в день рождения",
                            DiscountPercent = 15m,
                            EndDate = new DateTime(2027, 2, 22, 12, 58, 59, 34, DateTimeKind.Utc).AddTicks(1658),
                            ImageUrl = "/images/promos/birthday.jpg",
                            IsActive = true,
                            Name = "День рождения",
                            StartDate = new DateTime(2025, 2, 22, 12, 58, 59, 34, DateTimeKind.Utc).AddTicks(1657)
                        });
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.PromotionDish", b =>
                {
                    b.Property<int>("PromotionId")
                        .HasColumnType("integer");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.HasKey("PromotionId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("PromotionDishes");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Пользователь"
                        });
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.BonusAccount", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.User", "User")
                        .WithOne("BonusAccount")
                        .HasForeignKey("LoveSushiPMR.Models.Entities.BonusAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.CartItem", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoveSushiPMR.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Dish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.DeliveryAddress", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.DeliveryZone", "DeliveryZone")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("DeliveryZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoveSushiPMR.Models.Entities.User", "User")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("UserId");

                    b.Navigation("DeliveryZone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Dish", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Order", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.Courier", "Courier")
                        .WithMany("Orders")
                        .HasForeignKey("CourierId");

                    b.HasOne("LoveSushiPMR.Models.Entities.DeliveryAddress", "DeliveryAddress")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoveSushiPMR.Models.Entities.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoveSushiPMR.Models.Entities.PromoCode", "PromoCode")
                        .WithMany("Orders")
                        .HasForeignKey("PromoCodeId");

                    b.HasOne("LoveSushiPMR.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Payment");

                    b.Navigation("PromoCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.Dish", "Dish")
                        .WithMany("OrderItems")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoveSushiPMR.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.PromotionDish", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.Dish", "Dish")
                        .WithMany("PromotionDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoveSushiPMR.Models.Entities.Promotion", "Promotion")
                        .WithMany("PromotionDishes")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Review", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.Dish", "Dish")
                        .WithMany("Reviews")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoveSushiPMR.Models.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("LoveSushiPMR.Models.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.User", b =>
                {
                    b.HasOne("LoveSushiPMR.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Courier", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.DeliveryAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.DeliveryZone", b =>
                {
                    b.Navigation("DeliveryAddresses");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Dish", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("PromotionDishes");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Payment", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.PromoCode", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Promotion", b =>
                {
                    b.Navigation("PromotionDishes");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LoveSushiPMR.Models.Entities.User", b =>
                {
                    b.Navigation("BonusAccount");

                    b.Navigation("DeliveryAddresses");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
